### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by biodataganache** [PNNL-CompBio/Snekmer#43]
General issue to improve speed of pipeline, especially wrt large input files

**Comment by biodataganache** [comment]
Example from 'search' pipeline where I'm applying a model to ~700K protein sequences. Here are the log file times for each of the 3 steps in the 'snekmer model --until vectorize' run.
processed: 4:50 hours
labels:  0.5 s
features: 34 min

**Comment by biodataganache** [comment]
Follow up to see if this is a linear relationship: application of a model to 80K sequences runs in:
processed: 1 min 37s
labels: 0.83 s
features: 12 min

So - answer is NO - not linear at all.

**Comment by biodataganache** [comment]
Dropped print and time statements in to the snekmer/rules/process_input.smk code (preprocess rule) to assess timing with the 700K sequence file.
Fasta file read: 6 s (no problems here at all)
Looping through the sequences to - do stuff* (line 103-155)
Start (per 10K sequences): 20 s
End (per 10K sequences): 8-10 min
If this is multiplied by 70 it's close to the 4+ hour time.

Question is what is being done and why?
There's code to filter duplicates - but that's not a big deal I think (we could drop that). But it could be partly causing the gradual slowdown - since we're searching text through a longer and longer list of identifiers

[log.txt](https://github.com/PNNL-CompBio/Snekmer/files/8134073/log.txt)

**Comment by biodataganache** [comment]
Looking at the timing for things in the sequence filter loop (lines 103-155):




# first 10K - start of process
# loop (for 10k) is at ~3s
# filter duplicates (for 1) is at 129/1000000s of a sec
# json stuff (for 1) is at 139/1000000s of a sec     
...tick...
2022-02-24 08:15:56.128419
...jsonstuff...
2022-02-24 08:15:56.128432
2022-02-24 08:15:56.128503
...filter duplicates...
2022-02-24 08:15:56.128510
...filter duplicates...
2022-02-24 08:15:56.128649
...tick...
2022-02-24 08:15:58.916927

# loop later on (for 10k) is at about 2 min
# filter duplicates (for 1) is at: 3200/1000000
# json stuff (for 1) is at: 6551/1000000

...tick...
2022-02-24 08:32:03.998717
...jsonstuff...
2022-02-24 08:32:03.998743
2022-02-24 08:32:04.005294
...filter duplicates...
2022-02-24 08:32:04.005326
...filter duplicates...
2022-02-24 08:32:04.008520
...tick...
2022-02-24 08:33:59.891833

# and still later for 10K is at: 5 min 30 s
# filter duplicates: 14043/1000000s
# json stuff: 19857/1000000s

...tick...
2022-02-24 10:43:08.423627
...jsonstuff...
2022-02-24 10:43:08.423657
2022-02-24 10:43:08.443514
...filter duplicates...
2022-02-24 10:43:08.443543
...filter duplicates...
2022-02-24 10:43:08.457586
...tick...
2022-02-24 10:48:33.468109

**Comment by biodataganache** [comment]
Looking at the code it appears to me that the pre-processing step is mostly about filtering for duplicate entries (based only on the identifier from the sequence) and repackaging the fasta file and some parameters into a .json file that is then used in the vectorize rule. However, the vectorize rule essentially uses only a small part of the output from this step - and goes back to the fasta files to get the sequences anyway. There are kmer basis set that's used from the pre-processing, but for the 'search' mode (currently the Python script to do searching) I think essentially all of the preprocessing isn't necessary. So we just need a way to skip right to the vectorize step - *I think*

**Comment by christinehc** [comment]
Partially addressed by 1bf9c9d

**Comment by biodataganache** [comment]
Addressed by PR fix-speed
