### ISSUE TITLE
Clustering not working bc of fa_map and not FA_MAP

### ISSUE THREAD

**Issue by openpaul** [PNNL-CompBio/Snekmer#46]
Hello,

I wanted to give this a go with the clustering mode but are encountering an error message:

```
Building DAG of jobs...
InputFunctionException in line 118 of [...]miniconda3/envs/snekmer/lib/python3.10/site-packages/snekmer/rules/kmerize.smk:
Error:
  NameError: name 'fa_map' is not defined
Wildcards:
  nb=test_1
Traceback:
  File "[...]miniconda3/envs/snekmer/lib/python3.10/site-packages/snekmer/rules/cluster.smk", line 127, in <lambda>

```

I believe this relates to this line:
https://github.com/PNNL-CompBio/Snekmer/blob/23ad67bcb53aa660e616f6ef23c6e20da70aa021/snekmer/rules/cluster.smk#L127

Which should be `FA_MAP` instead of the lowercase `fa_map`?
Similar to here: https://github.com/PNNL-CompBio/Snekmer/blob/deb4b98750bd0fe895707dc581bc34994c538743/snekmer/rules/model.smk#L112

**Comment by christinehc** [comment]
Hi, thank you for bringing this to our attention. The erroneous references to the variable in question have been corrected, and I've made some other bugfixes to the clustering workflow. The cluster workflow should now work as intended; let me know if you run into further issues.
