### ISSUE TITLE
CLI - "snekmer model" failing on Score rule.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/Snekmer#54]
snekmer version is 1.0.0-beta.
I am using the input folder from Snekmer/resources/tutorial/demo_files.
I am using the config file from Snekmer/resources.

When running "snekmer model" on the command line, this successfully runs the vectorize step but then fails on the score step. 

Other notes:
When running dryrun "snekmer model -n", it appears to look successful (no red error messages).
 snekmer cluster works successfully with the same config file and input folder.

Here is the error output. I will provide more if requested. I know snakemake error messages aren't the best.

[Fri Aug  5 12:27:36 2022]
rule score:
    input: output/kmerize/NapD.kmers, output/vector/cNorB.npz, output/vector/NapB.npz, output/vector/nirS.npz, output/vector/NapD.npz
    output: output/scoring/sequences/NapD.csv.gz, output/scoring/weights/NapD.csv.gz, output/scoring/NapD.scorer
    log: output/scoring/log/NapD.log
    jobid: 12
    reason: Missing output files: output/scoring/weights/NapD.csv.gz, output/scoring/sequences/NapD.csv.gz; Input files updated by another job: output/vector/NapB.npz, output/vector/cNorB.npz, output/vector/NapD.npz, output/vector/nirS.npz, output/kmerize/NapD.kmers
    wildcards: nb=NapD
    resources: tmpdir=/var/folders/lv/6v82hnnx0q93y7_2qfxnqgdcgcvd0_/T

[Fri Aug  5 12:27:36 2022]
rule score:
    input: output/kmerize/cNorB.kmers, output/vector/cNorB.npz, output/vector/NapB.npz, output/vector/nirS.npz, output/vector/NapD.npz
    output: output/scoring/sequences/cNorB.csv.gz, output/scoring/weights/cNorB.csv.gz, output/scoring/cNorB.scorer
    log: output/scoring/log/cNorB.log
    jobid: 6
    reason: Missing output files: output/scoring/weights/cNorB.csv.gz, output/scoring/sequences/cNorB.csv.gz; Input files updated by another job: output/vector/NapB.npz, output/vector/cNorB.npz, output/vector/NapD.npz, output/kmerize/cNorB.kmers, output/vector/nirS.npz
    wildcards: nb=cNorB
    resources: tmpdir=/var/folders/lv/6v82hnnx0q93y7_2qfxnqgdcgcvd0_/T

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by christinehc** [comment]
@jjacobson95 Can you try reinstalling the snekmer environment and seeing if the issue is reproduced? I suspect this may be an artifact or combination of some of the other issues, which have now been resolved.

**Comment by jjacobson95** [comment]
I believe this is resolved. With the latest version, "snekmer model" and "snekmer cluster" are producing the expected output including figures.
