### ISSUE TITLE
Snekmer fails to run from a directory with a spacemark in the path. 

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/Snekmer#55]
When running from my OneDrive directory ("/Users/jaco059/OneDrive - PNNL/Desktop/Snekmer_Project"), this fails on the score and vectorize rules with the following error message:

/bin/sh: line 0: cd: /Users/jaco059/OneDrive: No such file or directory

Everything works fine when running from a directory path without spacemarks in it.

**Comment by christinehc** [comment]
@jjacobson95 Can you add which version of snakemake you have installed?

**Comment by jjacobson95** [comment]
This was for v1.0.0-beta

**Comment by christinehc** [comment]
@jjacobson95 Snakemake version, not Snekmer version

I believe this is an issue with newer versions of Snakemake. Will post an updated environment.yml soon that resolves the issue

**Comment by jjacobson95** [comment]
Thanks for resolving this - works on my end.
