### ISSUE TITLE
Documentation update - Expected file outputs.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/Snekmer#56]
This refers to the documentation [website](https://snekmer.readthedocs.io/en/latest/getting_started/modes.html#cluster-mode)

File outputs are currently outdated for "snekmer cluster", and likely the other modes too.

Current output folders (within "/path/to/output"):  cluster, kmerize, and vector. 
In cluster, I have snekmer.csv, log, and figures. Within figures, I have tsne.png, umap.png.
In kmerize, I have log, and files with (.kmers) suffix
In vector, I have files with (.npz) suffix.

**Comment by christinehc** [comment]
Resolved by #93
