### ISSUE TITLE
Possible issue - "Missing file outputs" message in "snekmer cluster" and "snekmer model" logs

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/Snekmer#57]
Version v1.0.0-beta
Mac OS
Input files from  Snekmer/resources/tutorial/demo_files/input
Config file from Snekmer/resources/config.yaml

Log generated from snakemake. Same type of messages are model and cluster. Not sure if this is an issue.

[snekmer_model.log](https://github.com/PNNL-CompBio/Snekmer/files/9292413/snekmer_model.log)

**Comment by christinehc** [comment]
Note: this is not an issue, simply the behavior of snakemake. See: https://snakemake.readthedocs.io/en/stable/executing/cli.html#OUTPUT
