### ISSUE TITLE
kmer-association learn workflow implementation

### ISSUE THREAD

**Issue by biodataganache** [PNNL-CompBio/Snekmer#70]
I've created a branch kmer-association for working on the feature we discussed. Added a test dataset for developing the method in resources.

**Comment by biodataganache** [comment]
kmer-association has a learn workflow and a (non-functional) learn.smk to house the code.
Still need to add reading annotation file and parsing that. Then everything else too.

**Comment by christinehc** [comment]
Closed (addressed by #115 )
